version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    restart: always
    ports:
      - "3000:80" # Frontend будет доступен на порту 3000
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/portfolio_db
    ports:
      - "8000:8000" # Backend будет доступен на порту 8000
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: portfolio-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local